FROM gcr.io/go-containerregistry/crane/debug:v0.22.1@sha256:e78770b31258a3846f878036d9c1f63fbe4c871f9f56990bf77fd95c013e3c1b
COPY --chmod=755 oci-index.sh /oci-index.sh
ENTRYPOINT ["/busybox/sh", "/oci-index.sh"]
